[project]
name = "llama-suite-comfyui"
description = "Manage and run llama.cpp server directly from ComfyUI for LLM generation."
version = "1.0.0"
license = { file = "LICENSE" }

[project.urls]
Repository = "https://github.com/YOUR_USERNAME/LlamaSuite"

# Used to prevent conflicts with other custom nodes
[tool.comfy]
PublisherId = "vizart-vj"
